-- Generated by Asghar Mustafa STUDENTID: 28905644 for FIT9132 Assignment 1B
-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-04-29 22:24:46 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


SET ECHO ON;

SPOOL mh_schema_output.txt

DROP SEQUENCE bed_allocation_bed_allocationi;

DROP SEQUENCE doctor_doctorid_seq;

DROP SEQUENCE nurse_nurseid_seq;

DROP SEQUENCE nurse_allocation_nurse_allocat;

DROP SEQUENCE patient_patientid_seq;

DROP SEQUENCE patient_pres_proced_patient_pr;


DROP TABLE admission CASCADE CONSTRAINTS;

DROP TABLE bed CASCADE CONSTRAINTS;

DROP TABLE bed_allocation CASCADE CONSTRAINTS;

DROP TABLE cost_center CASCADE CONSTRAINTS;

DROP TABLE doctor CASCADE CONSTRAINTS;

DROP TABLE doctor_speciaization CASCADE CONSTRAINTS;

DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE nurse CASCADE CONSTRAINTS;

DROP TABLE nurse_allocation CASCADE CONSTRAINTS;

DROP TABLE patient CASCADE CONSTRAINTS;

DROP TABLE patient_pres_proced CASCADE CONSTRAINTS;

DROP TABLE performing_doctor CASCADE CONSTRAINTS;

DROP TABLE prescribing_doctor CASCADE CONSTRAINTS;

DROP TABLE procedure CASCADE CONSTRAINTS;

DROP TABLE procedure_additional_item CASCADE CONSTRAINTS;

DROP TABLE specialization CASCADE CONSTRAINTS;

DROP TABLE ward CASCADE CONSTRAINTS;

CREATE TABLE admission ( 
--  PatientID: Unique Identifier for the patient at Monash Hospital
    patientid             NUMBER(7) NOT NULL, 
--  Date and Time the Patient is Admitted
    date_time_admission   DATE NOT NULL, 
--  Date and Time the patient is discharged
    date_time_discharge   DATE, 
--  Supervising DoctorID
    doctorid              NUMBER(7) NOT NULL
);

ALTER TABLE admission ADD CONSTRAINT admission_pk PRIMARY KEY ( date_time_admission,
                                                                patientid );

CREATE TABLE bed ( 
--  Bed Number in a given ward
    bed_no                NUMBER(3) NOT NULL, 
--  Ward Identifier
    ward_code             NUMBER(7) NOT NULL, 
--  Bedside Telephone Number
    "Bed_Telephone_No."   NUMBER(10) NOT NULL, 
--  Type of Bed
    bed_type              CHAR(1)
);

ALTER TABLE bed ADD CHECK ( bed_no > 0 );

ALTER TABLE bed ADD CONSTRAINT bed_pk PRIMARY KEY ( bed_no,
                                                    ward_code );

CREATE TABLE bed_allocation ( 
--  Surrogate key for Bed Allocation
    bed_allocationid           NUMBER(7) NOT NULL, 
--  Date and Time of Bed Allocation to the Patient
    date_time_allocation       DATE NOT NULL, 
--  Bed Number in a given ward
    bed_no                     NUMBER(3) NOT NULL, 
--  Ward Identifier
    ward_code                  NUMBER(7) NOT NULL, 
--  Date and Time the Patient is Admitted
    date_time_admission        DATE NOT NULL, 
--  PatientID: Unique Identifier for the patient at Monash Hospital
    patientid                  NUMBER(7) NOT NULL, 
--  Date and Time of Bed Allocation end for a given Bed allocation
    date_time_allocation_end   DATE
);

ALTER TABLE bed_allocation ADD CHECK ( bed_allocationid > 0 );

ALTER TABLE bed_allocation ADD CONSTRAINT bed_allocation_pk PRIMARY KEY ( bed_allocationid );

ALTER TABLE bed_allocation
    ADD CONSTRAINT bed_allocation_nk UNIQUE ( date_time_admission,
                                              patientid,
                                              bed_no,
                                              ward_code,
                                              date_time_allocation );

CREATE TABLE cost_center ( 
--  Unique Identifier for the cost Center
    cost_center_code    NUMBER(7) NOT NULL, 
--  Description of the  Cost center
    cost_center_title   VARCHAR2(50) NOT NULL, 
--  Manager of the Cost Center
    manager_name        VARCHAR2(50) NOT NULL
);

ALTER TABLE cost_center ADD CONSTRAINT cost_center_pk PRIMARY KEY ( cost_center_code );

CREATE TABLE doctor ( 
--  Supervising DoctorID
    doctorid       NUMBER(7) NOT NULL, 
--  Supervising Doctor Name
    doctor_name    VARCHAR2(50) NOT NULL, 
--  Phone Number of the Supervising doctor
    phone_number   CHAR(10) NOT NULL
);

ALTER TABLE doctor ADD CONSTRAINT "Doctor ID check" CHECK ( doctorid > 0 );

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctorid );

CREATE TABLE doctor_speciaization ( 
--  Specialization Identifier
    specialzation_name   VARCHAR2(50) NOT NULL, 
--  Supervising DoctorID
    doctorid             NUMBER(7) NOT NULL
);

ALTER TABLE doctor_speciaization ADD CONSTRAINT doctor_speciaization_pk PRIMARY KEY ( doctorid,
                                                                                      specialzation_name );

CREATE TABLE item ( 
--  Unique identifier of "extra" items in the procedure
    item_code          NUMBER(7) NOT NULL, 
--  What the item is about
    description        VARCHAR2(50) NOT NULL, 
--  The number of the item remaining in stock
    current_stock      NUMBER(3) NOT NULL, 
--  The price of the item
    price              NUMBER(4) NOT NULL, 
--  Unique Identifier for the cost Center
    cost_center_code   NUMBER(7) NOT NULL
);

ALTER TABLE item ADD CONSTRAINT item_pk PRIMARY KEY ( item_code );

CREATE TABLE nurse ( 
--  Unique Nurse Identifier
    nurseid              NUMBER(7) NOT NULL, 
--  First Name of the Nurse
    first_name           VARCHAR2(50) NOT NULL, 
--  Last Name of the Nurse 
    last_name            VARCHAR2(50) NOT NULL, 
--  Contact Number of the Nurse
    contact_phone        CHAR(10) NOT NULL, 
--  Is the Nurse Certified to work with Children?
    certified_children   CHAR(1) NOT NULL
);

ALTER TABLE nurse ADD CONSTRAINT "Nurse ID" CHECK ( nurseid > 0 );

ALTER TABLE nurse ADD CONSTRAINT nurse_pk PRIMARY KEY ( nurseid );

CREATE TABLE nurse_allocation ( 
--  Surrogate Key for Nurse Allocation
    nurse_allocationid   NUMBER(7) NOT NULL, 
--  Date of Ward Assigned to the Nurse
    date_assigned        DATE NOT NULL, 
--  Date the assignment was completed
    date_complete        DATE NOT NULL, 
--  Ward Identifier
    ward_code            NUMBER(7) NOT NULL, 
--  Unique Nurse Identifier
    nurseid              NUMBER(7) NOT NULL
);

ALTER TABLE nurse_allocation ADD CHECK ( nurse_allocationid > 0 );

ALTER TABLE nurse_allocation ADD CONSTRAINT nurse_allocation_pk PRIMARY KEY ( nurse_allocationid );

ALTER TABLE nurse_allocation
    ADD CONSTRAINT nurse_allocation_nk UNIQUE ( date_assigned,
                                                date_complete,
                                                nurseid,
                                                ward_code );

CREATE TABLE patient ( 
--  PatientID: Unique Identifier for the patient at Monash Hospital
    patientid          NUMBER(7) NOT NULL, 
--  Patient Name
    patient_name       VARCHAR2(50) NOT NULL, 
--  Patient's Resedential Addres
    address            VARCHAR2(50) NOT NULL, 
--  Patient's Date of Birth
    date_of_birth      DATE NOT NULL, 
--  Emergency Contact Number for a Patient
    emergency_number   CHAR(10) NOT NULL
);

ALTER TABLE patient ADD CONSTRAINT "Positive values for PatientID" CHECK ( patientid > 0 );

ALTER TABLE patient ADD CONSTRAINT patient_pk PRIMARY KEY ( patientid );

CREATE TABLE patient_pres_proced ( 
--  surrogate key for Patient Prescription
    patient_presid        NUMBER(7) NOT NULL, 
--  PatientID: Unique Identifier for the patient at Monash Hospital
    patientid             NUMBER(7) NOT NULL, 
--  Date and Time the Patient is Admitted
    date_time_admission   DATE NOT NULL, 
--  Unique Identifier for procedure in Hospital
    procedure_code        NUMBER(7) NOT NULL, 
--  Doctor ID of the Prescribing Doctor
    requested_doctorid    NUMBER(7) NOT NULL, 
--  Performing Doctor ID
    performing_doctorid   NUMBER(7) NOT NULL, 
--  Date and Time when the procedure is scheduled
    date_time_procedure   DATE NOT NULL
);

ALTER TABLE patient_pres_proced ADD CHECK ( patient_presid > 0 );

ALTER TABLE patient_pres_proced ADD CONSTRAINT patient_pres_proced_pk PRIMARY KEY ( patient_presid );

ALTER TABLE patient_pres_proced
    ADD CONSTRAINT patient_pres_proced_nk UNIQUE ( procedure_code,
                                                   patientid,
                                                   date_time_admission );

CREATE TABLE performing_doctor ( 
--  Performing Doctor ID
    performing_doctorid      NUMBER(7) NOT NULL, 
--  Name of Performing Doctor or the Doctor Incharge
    performing_doctor_name   VARCHAR2(50) NOT NULL
);

ALTER TABLE performing_doctor ADD CONSTRAINT performing_doctor_pk PRIMARY KEY ( performing_doctorid );

CREATE TABLE prescribing_doctor ( 
--  Doctor ID of the Prescribing Doctor
    requested_doctorid      NUMBER(7) NOT NULL, 
--  Name of Prescribing Doctor
    requested_doctor_name   VARCHAR2(50) NOT NULL
);

ALTER TABLE prescribing_doctor ADD CONSTRAINT prescribing_doctor_pk PRIMARY KEY ( requested_doctorid );

CREATE TABLE procedure ( 
--  Unique Identifier for procedure in Hospital
    procedure_code     NUMBER(7) NOT NULL, 
--  Name of procedure
    procedure_name     VARCHAR2(50) NOT NULL, 
--  Price of Procedure
    procedure_charge   NUMBER(6, 2) NOT NULL
);

ALTER TABLE procedure ADD CHECK ( procedure_code > 0 );

ALTER TABLE procedure ADD CONSTRAINT procedure_pk PRIMARY KEY ( procedure_code );

CREATE TABLE procedure_additional_item ( 
--  Unique identifier of "extra" items in the procedure
    item_code           NUMBER(7) NOT NULL, 
--  surrogate key for Patient Prescription
    patient_presid      NUMBER(7) NOT NULL, 
--  Quantity of Item used in the given procedure
    quantity            NUMBER(3) NOT NULL, 
--  Charge of Item used in the the procedure
    total_item_charge   NUMBER(6, 2) NOT NULL
);

ALTER TABLE procedure_additional_item ADD CONSTRAINT procedure_additional_item_pk PRIMARY KEY ( item_code,
                                                                                                patient_presid );

CREATE TABLE specialization ( 
--  Specialization Identifier
    specialzation_name VARCHAR2(50) NOT NULL
);

ALTER TABLE specialization ADD CONSTRAINT specialization_pk PRIMARY KEY ( specialzation_name );

CREATE TABLE ward ( 
--  Ward Identifier
    ward_code          NUMBER(7) NOT NULL, 
--  Name of the Ward
    ward_name          VARCHAR2(50) NOT NULL, 
--  Number of Beds in the Ward
    number_beds        NUMBER(3) NOT NULL, 
--  Number of Free Beds in the Ward
    number_free_beds   NUMBER(3) NOT NULL
);

ALTER TABLE ward ADD CONSTRAINT "Ward Code Value" CHECK ( ward_code > 0 );

ALTER TABLE ward ADD CONSTRAINT "Beds check" CHECK ( number_beds > 0 );

ALTER TABLE ward ADD CONSTRAINT "Free Beds Check" CHECK ( number_free_beds >= 0 );

ALTER TABLE ward ADD CONSTRAINT ward_pk PRIMARY KEY ( ward_code );

ALTER TABLE bed_allocation
    ADD CONSTRAINT admission_bed_allocation FOREIGN KEY ( date_time_admission,
                                                          patientid )
        REFERENCES admission ( date_time_admission,
                               patientid );

ALTER TABLE admission
    ADD CONSTRAINT admission_doctor FOREIGN KEY ( doctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE patient_pres_proced
    ADD CONSTRAINT admit_patient_proced FOREIGN KEY ( date_time_admission,
                                                      patientid )
        REFERENCES admission ( date_time_admission,
                               patientid );

ALTER TABLE bed_allocation
    ADD CONSTRAINT bed_bed_allocation FOREIGN KEY ( bed_no,
                                                    ward_code )
        REFERENCES bed ( bed_no,
                         ward_code );

ALTER TABLE item
    ADD CONSTRAINT cost_center_item FOREIGN KEY ( cost_center_code )
        REFERENCES cost_center ( cost_center_code );

ALTER TABLE doctor_speciaization
    ADD CONSTRAINT doctor_doctor_specialization FOREIGN KEY ( doctorid )
        REFERENCES doctor ( doctorid );

ALTER TABLE procedure_additional_item
    ADD CONSTRAINT item_procedure_additional_item FOREIGN KEY ( item_code )
        REFERENCES item ( item_code );

ALTER TABLE nurse_allocation
    ADD CONSTRAINT nurse_nurse_allocation FOREIGN KEY ( nurseid )
        REFERENCES nurse ( nurseid );

ALTER TABLE admission
    ADD CONSTRAINT patient_admission FOREIGN KEY ( patientid )
        REFERENCES patient ( patientid );

ALTER TABLE procedure_additional_item
    ADD CONSTRAINT patient_proced_add_item FOREIGN KEY ( patient_presid )
        REFERENCES patient_pres_proced ( patient_presid );

ALTER TABLE patient_pres_proced
    ADD CONSTRAINT perf_doc_proced FOREIGN KEY ( performing_doctorid )
        REFERENCES performing_doctor ( performing_doctorid );

ALTER TABLE patient_pres_proced
    ADD CONSTRAINT prec_doc_proced FOREIGN KEY ( requested_doctorid )
        REFERENCES prescribing_doctor ( requested_doctorid );

ALTER TABLE patient_pres_proced
    ADD CONSTRAINT proced_patient_proced FOREIGN KEY ( procedure_code )
        REFERENCES procedure ( procedure_code );

ALTER TABLE doctor_speciaization
    ADD CONSTRAINT spec_doc_spec FOREIGN KEY ( specialzation_name )
        REFERENCES specialization ( specialzation_name );

ALTER TABLE bed
    ADD CONSTRAINT ward_bed FOREIGN KEY ( ward_code )
        REFERENCES ward ( ward_code );

ALTER TABLE nurse_allocation
    ADD CONSTRAINT ward_nurse_allocation FOREIGN KEY ( ward_code )
        REFERENCES ward ( ward_code );

CREATE SEQUENCE bed_allocation_bed_allocationi START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE doctor_doctorid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE nurse_nurseid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE nurse_allocation_nurse_allocat START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE patient_patientid_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE patient_pres_proced_patient_pr START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
 
SET ECHO OFF;